(()=>{if(!document.querySelector('link[href="links.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='links.css';document.head.appendChild(l)}})();
function validHttpUrl(value){try{const u=new URL(value);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
function addPurchaseLinkRow(data={}){const box=document.getElementById('purchaseLinks');if(!box)return;const row=document.createElement('div');row.className='purchase-link-row';row.innerHTML=`<input class="purchase-label" placeholder="Loja / botão (ex.: Amazon)" value="${esc(data.label||'')}"><input class="purchase-url" type="url" placeholder="https://..." value="${esc(data.url||'')}"><label class="affiliate-check"><input class="purchase-affiliate" type="checkbox" ${data.is_affiliate?'checked':''}> Comissionado</label><button class="secondary" type="button" onclick="this.closest('.purchase-link-row').remove()">Remover</button>`;box.appendChild(row)}
function renderPurchaseLinks(rows=[]){const box=document.getElementById('purchaseLinks');if(!box)return;box.innerHTML='';(rows.length?rows:[{}]).forEach(addPurchaseLinkRow)}
function setupReviewVideosUI(){const legacy=document.querySelector('[name="youtube_review_url"]');if(!legacy||document.getElementById('reviewVideos'))return;const field=legacy.closest('.field');if(!field)return;field.innerHTML=`<label>Resenhas / vídeos no YouTube</label><div id="reviewVideos"></div><button class="secondary" type="button" onclick="addReviewVideoRow()" style="margin-top:9px;align-self:flex-start">+ Adicionar outro vídeo</button><small class="muted">Cadastre quantos vídeos quiser. O título é opcional e pode identificar o canal, a pauta ou o tipo de vídeo.</small>`}
function addReviewVideoRow(data={}){const box=document.getElementById('reviewVideos');if(!box)return;const row=document.createElement('div');row.className='review-video-row';row.innerHTML=`<input class="review-label" placeholder="Título opcional (ex.: Minha resenha)" value="${esc(data.label||'')}"><input class="review-url" type="url" placeholder="https://www.youtube.com/watch?v=..." value="${esc(data.url||'')}"><button class="secondary" type="button" onclick="this.closest('.review-video-row').remove()">Remover</button>`;box.appendChild(row)}
function renderReviewVideos(rows=[]){setupReviewVideosUI();const box=document.getElementById('reviewVideos');if(!box)return;box.innerHTML='';(rows.length?rows:[{}]).forEach(addReviewVideoRow)}
function collectReviewVideos(){const rows=[...document.querySelectorAll('.review-video-row')].map((r,i)=>({label:r.querySelector('.review-label').value.trim(),url:r.querySelector('.review-url').value.trim(),sort_order:i})).filter(x=>x.label||x.url);for(const x of rows){if(!x.url)throw new Error('Informe a URL em todas as linhas de vídeo utilizadas.');if(!validHttpUrl(x.url))throw new Error('Confira os links dos vídeos: use URLs iniciadas por http:// ou https://.')}return rows}
async function persistBookLinks(bookId,reviewRows){const rows=[...document.querySelectorAll('.purchase-link-row')].map((r,i)=>({label:r.querySelector('.purchase-label').value.trim(),url:r.querySelector('.purchase-url').value.trim(),is_affiliate:r.querySelector('.purchase-affiliate').checked,sort_order:i})).filter(x=>x.label||x.url);for(const x of rows){if(!x.label)throw new Error('Informe o nome da loja em todos os links de compra.');if(!validHttpUrl(x.url))throw new Error(`Link de compra inválido para “${x.label}”.`)}let {error}=await sbAdmin.from('book_purchase_links').delete().eq('book_id',bookId);if(error)throw error;if(rows.length){({error}=await sbAdmin.from('book_purchase_links').insert(rows.map(x=>({book_id:bookId,...x}))));if(error)throw error}({error}=await sbAdmin.from('book_review_videos').delete().eq('book_id',bookId));if(error)throw error;if(reviewRows.length){({error}=await sbAdmin.from('book_review_videos').insert(reviewRows.map(x=>({book_id:bookId,...x}))));if(error)throw error}({error}=await sbAdmin.from('books').update({youtube_review_url:reviewRows[0]?.url||null}).eq('id',bookId));if(error)throw error}
const _bbOriginalSaveBook=window.saveBook;
window.saveBook=async function(e){const f=e.target,fd=new FormData(f),existingId=String(fd.get('book_id')||''),title=String(fd.get('title')||'').trim(),author=String(fd.get('author')||'').trim();const linkSnapshot=[...document.querySelectorAll('.purchase-link-row')].map(r=>({label:r.querySelector('.purchase-label').value,url:r.querySelector('.purchase-url').value,affiliate:r.querySelector('.purchase-affiliate').checked}));let reviewSnapshot=[];try{for(const x of linkSnapshot){if((x.label||x.url)&&(!x.label||!validHttpUrl(x.url)))throw new Error('Confira os links de compra: cada linha usada precisa de nome da loja e URL válida.')}reviewSnapshot=collectReviewVideos()}catch(err){e.preventDefault();msg(err.message,'error');return}await _bbOriginalSaveBook(e);if(document.getElementById('status')?.classList.contains('error'))return;let bookId=existingId;if(!bookId){const {data:a}=await sbAdmin.from('authors').select('id').eq('name',author).maybeSingle();let q=sbAdmin.from('books').select('id').eq('title',title).order('created_at',{ascending:false}).limit(1);if(a?.id)q=q.eq('author_id',a.id);const {data}=await q.maybeSingle();bookId=data?.id||''}if(!bookId){msg('Livro salvo, mas não consegui vincular os links automaticamente. Abra o livro em Editar e salve novamente.','error');return}try{renderPurchaseLinks(linkSnapshot.map(x=>({label:x.label,url:x.url,is_affiliate:x.affiliate})));renderReviewVideos(reviewSnapshot);await persistBookLinks(bookId,reviewSnapshot);msg(existingId?'Livro, links e vídeos atualizados com sucesso.':'Livro, links e vídeos cadastrados com sucesso.','ok');newBook(false)}catch(err){console.error(err);msg('Livro salvo, mas houve erro nos links ou vídeos: '+(err.message||err),'error')}};
const _bbOriginalEditBook=window.editBook;
window.editBook=async function(id){await _bbOriginalEditBook(id);const [{data:links},{data:videos},{data:book}]=await Promise.all([sbAdmin.from('book_purchase_links').select('id,label,url,is_affiliate,sort_order').eq('book_id',id).order('sort_order'),sbAdmin.from('book_review_videos').select('id,label,url,sort_order').eq('book_id',id).order('sort_order'),sbAdmin.from('books').select('youtube_review_url').eq('id',id).single()]);renderPurchaseLinks(links||[]);const reviewRows=(videos&&videos.length)?videos:(book?.youtube_review_url?[{label:'Resenha recomendada',url:book.youtube_review_url,sort_order:0}]:[]);renderReviewVideos(reviewRows)};
const _bbOriginalNewBook=window.newBook;
window.newBook=function(clearMessage=true){_bbOriginalNewBook(clearMessage);renderPurchaseLinks([]);renderReviewVideos([])};
document.addEventListener('DOMContentLoaded',()=>{setupReviewVideosUI();renderPurchaseLinks([]);renderReviewVideos([])});