const sbAdmin=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
let allCategories=[],allTags=[];
function msg(text,kind="note"){const e=document.getElementById("status");e.className="note "+kind;e.textContent=text;e.classList.remove("hidden")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function currentAdmin(){const {data:{user}}=await sbAdmin.auth.getUser();if(!user)return null;const {data,error}=await sbAdmin.from("profiles").select("is_admin").eq("id",user.id).maybeSingle();if(error||!data?.is_admin)return null;return user}
async function updateUI(){const user=await currentAdmin();document.getElementById("loginPanel").classList.toggle("hidden",!!user);document.getElementById("adminPanel").classList.toggle("hidden",!user);if(user){document.getElementById("adminEmail").textContent=user.email||"";await populateSelects();await renderTable()}}
async function login(e){e.preventDefault();const fd=new FormData(e.target);const {error}=await sbAdmin.auth.signInWithPassword({email:fd.get("email"),password:fd.get("password")});if(error){msg("Login não realizado: "+error.message,"error");return}const user=await currentAdmin();if(!user){await sbAdmin.auth.signOut();msg("Esta conta não está autorizada como administradora.","error");return}msg("Login realizado.","ok");await updateUI()}
async function logout(){await sbAdmin.auth.signOut();await updateUI()}
function ensureRelationFields(){
  const form=document.getElementById('bookForm');if(!form)return;
  const author=form.elements.author;
  if(author&&!form.elements.additional_authors){author.closest('.field')?.insertAdjacentHTML('afterend','<div class="field"><label>Autores adicionais</label><input name="additional_authors" placeholder="Separe por ponto e vírgula"><small class="muted">Use apenas quando a obra tiver mais de um autor.</small></div>')}
  const series=form.elements.series;
  if(series&&!form.elements.additional_series){series.closest('.field')?.insertAdjacentHTML('afterend','<div class="field full"><label>Séries adicionais</label><textarea name="additional_series" placeholder="Nome da série | volume\nOutra série | 2"></textarea><small class="muted">Uma por linha (ou separadas por ponto e vírgula). Formato: Nome da série | volume. Útil para livros que pertencem a mais de uma série.</small></div>')}
}
async function populateSelects(){const [cats,cols,tags]=await Promise.all([sbAdmin.from("categories").select("id,name,area").order("name"),sbAdmin.from("collections").select("id,name").order("name"),sbAdmin.from("tags").select("id,name").order("name")]);allCategories=cats.data||[];allTags=tags.data||[];document.getElementById("collectionId").innerHTML='<option value="">Sem coleção editorial</option>'+((cols.data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(""));filterCategories();renderTags()}
function filterCategories(selected=[]){const area=document.getElementById("areaSelect")?.value,box=document.getElementById("categoryChecks");if(!box)return;const rows=allCategories.filter(x=>x.area===area);box.innerHTML=rows.length?rows.map(x=>`<label class="chip selectable-chip"><input type="checkbox" name="category_ids" value="${x.id}" ${selected.includes(x.id)?"checked":""}> ${esc(x.name)}</label>`).join(""):'<span class="muted">Ainda não há categorias nesta área.</span>'}
function renderTags(selected=[]){const box=document.getElementById("tagChecks");if(!box)return;box.innerHTML=allTags.length?allTags.map(x=>`<label class="chip selectable-chip tag-select"><input type="checkbox" name="tag_ids" value="${x.id}" ${selected.includes(x.id)?"checked":""}> ${esc(x.name)}</label>`).join(""):'<span class="muted">Ainda não há temas cadastrados.</span>'}
async function findOrCreate(table,nameField,value,extra={}){if(!value)return null;let {data,error}=await sbAdmin.from(table).select("id").eq(nameField,value).maybeSingle();if(error)throw error;if(data)return data.id;({data,error}=await sbAdmin.from(table).insert({[nameField]:value,...extra}).select("id").single());if(error)throw error;return data.id}
async function uploadCover(file){if(!file||!file.size)return null;if(file.size>5*1024*1024)throw new Error("A capa deve ter no máximo 5 MB.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Formato inválido. Use JPG, PNG ou WebP.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`edicoes-br/${crypto.randomUUID()}.${ext}`;const {error}=await sbAdmin.storage.from("book-covers").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return sbAdmin.storage.from("book-covers").getPublicUrl(path).data.publicUrl}
function parseAdditionalAuthors(v){return String(v||'').split(';').map(x=>x.trim()).filter(Boolean)}
function parseAdditionalSeries(v){return String(v||'').split(/[;\n]+/).map(x=>x.trim()).filter(Boolean).map(row=>{const parts=row.split('|').map(x=>x.trim());const n=parts[1]?Number(String(parts[1]).replace(',','.')):null;return{name:parts[0],volume:Number.isFinite(n)?n:null}}).filter(x=>x.name)}
async function syncBookAuthors(bookId,primaryAuthorId,additionalNames=[]){
  const rows=[];if(primaryAuthorId)rows.push({book_id:bookId,author_id:primaryAuthorId,author_order:0,is_primary:true});
  let order=1;const seen=new Set(primaryAuthorId?[primaryAuthorId]:[]);
  for(const name of additionalNames){const id=await findOrCreate('authors','name',name);if(!id||seen.has(id))continue;seen.add(id);rows.push({book_id:bookId,author_id:id,author_order:order++,is_primary:false})}
  let {error}=await sbAdmin.from('book_authors').delete().eq('book_id',bookId);if(error)throw error;
  if(rows.length){({error}=await sbAdmin.from('book_authors').insert(rows));if(error)throw error}
}
async function syncBookSeries(bookId,primarySeriesId,primaryVolume,additional=[]){
  const rows=[];if(primarySeriesId)rows.push({book_id:bookId,series_id:primarySeriesId,series_volume:primaryVolume??null,is_primary:true});
  const seen=new Set(primarySeriesId?[primarySeriesId]:[]);
  for(const item of additional){const id=await findOrCreate('series','name',item.name);if(!id||seen.has(id))continue;seen.add(id);rows.push({book_id:bookId,series_id:id,series_volume:item.volume??null,is_primary:false})}
  let {error}=await sbAdmin.from('book_series').delete().eq('book_id',bookId);if(error)throw error;
  if(rows.length){({error}=await sbAdmin.from('book_series').insert(rows));if(error)throw error}
}
async function saveBook(e){
  e.preventDefault();const f=e.target,fd=new FormData(f),bookId=String(fd.get("book_id")||"");
  try{
    msg(bookId?"Atualizando livro…":"Salvando livro…");
    const author_id=await findOrCreate("authors","name",String(fd.get("author")||"").trim());
    const additionalAuthors=parseAdditionalAuthors(fd.get('additional_authors'));
    const seriesName=String(fd.get("series")||"").trim();const series_id=seriesName?await findOrCreate("series","name",seriesName):null;
    const primaryVolume=fd.get("series_volume")?Number(fd.get("series_volume")):null;
    const additionalSeries=parseAdditionalSeries(fd.get('additional_series'));
    if(series_id){const seriesPayload={brazil_published_volumes:fd.get("brazil_published_volumes")?Number(fd.get("brazil_published_volumes")):null,brazil_status:String(fd.get("brazil_status")||"").trim()||null,original_name:String(fd.get("series_original_name")||"").trim()||null,original_total_volumes:fd.get("original_total_volumes")?Number(fd.get("original_total_volumes")):null,total_volumes:fd.get("original_total_volumes")?Number(fd.get("original_total_volumes")):null};const {error}=await sbAdmin.from("series").update(seriesPayload).eq("id",series_id);if(error)throw error}
    const newCover=await uploadCover(fd.get("cover_file"));
    const payload={title:String(fd.get("title")||"").trim(),original_title:String(fd.get("original_title")||"").trim()||null,author_id,series_id,series_volume:primaryVolume,area:fd.get("area"),original_year:fd.get("original_year")?Number(fd.get("original_year")):null,synopsis:String(fd.get("synopsis")||"").trim()||null};if(newCover)payload.cover_url=newCover;
    let id=bookId;if(bookId){const {error}=await sbAdmin.from("books").update(payload).eq("id",bookId);if(error)throw error}else{if(!newCover)payload.cover_url=null;const {data,error}=await sbAdmin.from("books").insert(payload).select("id").single();if(error)throw error;id=data.id}
    await syncBookAuthors(id,author_id,additionalAuthors);await syncBookSeries(id,series_id,primaryVolume,additionalSeries);
    let {error}=await sbAdmin.from("book_categories").delete().eq("book_id",id);if(error)throw error;const cats=fd.getAll("category_ids").filter(Boolean);if(cats.length){({error}=await sbAdmin.from("book_categories").insert(cats.map(category_id=>({book_id:id,category_id}))));if(error)throw error}
    ({error}=await sbAdmin.from("book_tags").delete().eq("book_id",id));if(error)throw error;const tags=fd.getAll("tag_ids").filter(Boolean);if(tags.length){({error}=await sbAdmin.from("book_tags").insert(tags.map(tag_id=>({book_id:id,tag_id}))));if(error)throw error}
    ({error}=await sbAdmin.from("book_collections").delete().eq("book_id",id));if(error)throw error;const collectionId=fd.get("collection_id");if(collectionId){({error}=await sbAdmin.from("book_collections").insert({book_id:id,collection_id:collectionId,collection_number:String(fd.get("collection_number")||"").trim()||null}));if(error)throw error}
    const edition={book_id:id,country:"Brasil",publisher:String(fd.get("publisher")||"").trim()||null,publication_year:fd.get("publication_year")?Number(fd.get("publication_year")):null,isbn:String(fd.get("isbn")||"").trim()||null,translator:String(fd.get("translator")||"").trim()||null,pages:fd.get("pages")?Number(fd.get("pages")):null,notes:String(fd.get("edition_notes")||"").trim()||null,is_primary:true};if(newCover)edition.cover_url=newCover;const hasEdition=edition.publisher||edition.publication_year||edition.isbn||edition.translator||edition.pages||edition.notes||newCover;
    if(hasEdition){const {data:primary,error:pe}=await sbAdmin.from("editions").select("id,cover_url").eq("book_id",id).eq("country","Brasil").eq("is_primary",true).maybeSingle();if(pe)throw pe;if(primary){if(!edition.cover_url)delete edition.cover_url;({error}=await sbAdmin.from("editions").update(edition).eq("id",primary.id));if(error)throw error}else{({error}=await sbAdmin.from("editions").insert(edition));if(error)throw error}}
    msg(bookId?"Livro atualizado com sucesso.":"Livro cadastrado com sucesso.","ok");newBook(false);await renderTable()
  }catch(err){console.error(err);msg("Erro ao salvar: "+(err.message||err),"error")}
}
function newBook(clearMessage=true){const f=document.getElementById("bookForm");f.reset();f.elements.book_id.value="";document.getElementById("formTitle").textContent="Adicionar livro";document.getElementById("saveButton").textContent="Salvar livro";filterCategories();renderTags();if(clearMessage)document.getElementById("status").classList.add("hidden");window.scrollTo({top:0,behavior:"smooth"})}
async function editBook(id){
  msg("Carregando cadastro…");const {data:b,error}=await sbAdmin.from("books").select("*,authors(name),series(*),book_authors(author_order,is_primary,authors(id,name)),book_series(series_volume,is_primary,series(id,name)),book_categories(category_id),book_tags(tag_id),book_collections(collection_id,collection_number),editions(*)").eq("id",id).single();if(error){msg("Não foi possível abrir o livro: "+error.message,"error");return}
  ensureRelationFields();const f=document.getElementById("bookForm");const authorLinks=(b.book_authors||[]).slice().sort((a,z)=>(a.author_order??999)-(z.author_order??999));const primaryAuthor=authorLinks.find(x=>x.is_primary)||authorLinks[0];const extraAuthors=authorLinks.filter(x=>x!==primaryAuthor).map(x=>x.authors?.name).filter(Boolean);
  const seriesLinks=(b.book_series||[]).slice().sort((a,z)=>(z.is_primary?1:0)-(a.is_primary?1:0));const primarySeries=seriesLinks.find(x=>x.is_primary)||seriesLinks[0];const extraSeries=seriesLinks.filter(x=>x!==primarySeries).map(x=>`${x.series?.name||''}${x.series_volume!=null?` | ${x.series_volume}`:''}`).filter(Boolean);
  f.elements.book_id.value=b.id;f.elements.title.value=b.title||"";f.elements.author.value=primaryAuthor?.authors?.name||b.authors?.name||"";f.elements.additional_authors.value=extraAuthors.join('; ');f.elements.original_title.value=b.original_title||"";f.elements.original_year.value=b.original_year||"";f.elements.synopsis.value=b.synopsis||"";f.elements.area.value=b.area||"Ficção Histórica";f.elements.series.value=primarySeries?.series?.name||b.series?.name||"";f.elements.series_volume.value=primarySeries?.series_volume??b.series_volume??"";f.elements.additional_series.value=extraSeries.join('\n');const s=primarySeries?.series?.id?await sbAdmin.from('series').select('*').eq('id',primarySeries.series.id).single():{data:b.series};const seriesMeta=s.data||b.series||{};f.elements.brazil_published_volumes.value=seriesMeta.brazil_published_volumes||"";f.elements.brazil_status.value=seriesMeta.brazil_status||"";f.elements.series_original_name.value=seriesMeta.original_name||"";f.elements.original_total_volumes.value=seriesMeta.original_total_volumes||seriesMeta.total_volumes||"";
  const col=b.book_collections?.[0];f.elements.collection_id.value=col?.collection_id||"";f.elements.collection_number.value=col?.collection_number||"";const br=(b.editions||[]).filter(x=>x.country==="Brasil");const ed=br.find(x=>x.is_primary)||br.sort((a,z)=>new Date(a.created_at)-new Date(z.created_at))[0];f.elements.publisher.value=ed?.publisher||"";f.elements.publication_year.value=ed?.publication_year||"";f.elements.isbn.value=ed?.isbn||"";f.elements.translator.value=ed?.translator||"";f.elements.pages.value=ed?.pages||"";f.elements.edition_notes.value=ed?.notes||"";filterCategories((b.book_categories||[]).map(x=>x.category_id));renderTags((b.book_tags||[]).map(x=>x.tag_id));document.getElementById("formTitle").textContent="Editar livro";document.getElementById("saveButton").textContent="Salvar alterações";msg("Cadastro aberto para edição.","ok");window.scrollTo({top:0,behavior:"smooth"})
}
function relationAuthorText(b){const rows=(b.book_authors||[]).slice().sort((a,z)=>(a.author_order??999)-(z.author_order??999)).map(x=>x.authors?.name).filter(Boolean);return rows.join(' & ')||b.authors?.name||'—'}
function relationSeriesText(b){const rows=(b.book_series||[]).slice().sort((a,z)=>(z.is_primary?1:0)-(a.is_primary?1:0)).map(x=>x.series?.name).filter(Boolean);return rows.join(' • ')||b.series?.name||'—'}
async function renderTable(){const t=document.getElementById("adminTable"),q=(document.getElementById("adminSearch")?.value||"").trim().toLowerCase();const {data,error}=await sbAdmin.from("books").select("id,title,area,authors(name),series(name),book_authors(author_order,is_primary,authors(name)),book_series(is_primary,series(name)),editions(publisher,publication_year,is_primary,country)").order("created_at",{ascending:false}).limit(5000);if(error){t.innerHTML='<tr><td colspan="5">Erro ao carregar.</td></tr>';return}const rows=(data||[]).filter(b=>!q||`${b.title} ${relationAuthorText(b)} ${relationSeriesText(b)}`.toLowerCase().includes(q));t.innerHTML=rows.length?rows.map(b=>{const br=(b.editions||[]).find(e=>e.country==="Brasil"&&e.is_primary)||(b.editions||[]).find(e=>e.country==="Brasil");const pub=[br?.publisher,br?.publication_year].filter(Boolean).join(" · ")||"—";return `<tr><td>${esc(b.title)}</td><td>${esc(relationAuthorText(b))}</td><td>${esc(pub)}</td><td>${esc(relationSeriesText(b))}</td><td><button class="secondary" onclick="editBook('${b.id}')">Editar</button> <button class="secondary" onclick="deleteBook('${b.id}')">Excluir</button></td></tr>`}).join(""):'<tr><td colspan="5">Nenhum livro cadastrado.</td></tr>'}
async function deleteBook(id){if(!confirm("Excluir este livro e seus relacionamentos? Esta ação não pode ser desfeita."))return;const {error}=await sbAdmin.from("books").delete().eq("id",id);if(error){msg("Erro ao excluir: "+error.message,"error");return}msg("Livro excluído.","ok");await renderTable()}
function patchSpreadsheetImporter(){
  const original=window.upsertImportedRow;if(typeof original!=='function'||original.__bbRelationsPatched)return;
  const wrapped=async function(r){await original(r);try{const {data:a}=await sbAdmin.from('authors').select('id').eq('name',r.author).maybeSingle();if(!a?.id)return;let q=sbAdmin.from('books').select('id,author_id,series_id,series_volume').eq('title',r.title).eq('author_id',a.id).order('created_at',{ascending:false}).limit(1);const {data:b}=await q.maybeSingle();if(!b?.id)return;await syncBookAuthors(b.id,b.author_id,[]);await syncBookSeries(b.id,b.series_id,b.series_volume,[])}catch(err){console.error('Falha ao sincronizar relações da importação',err)}};
  wrapped.__bbRelationsPatched=true;window.upsertImportedRow=wrapped;
}
document.addEventListener("DOMContentLoaded",()=>{ensureRelationFields();patchSpreadsheetImporter();updateUI()});
