const sbAuthor=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function primaryBrEdition(b){return (b.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(b.editions||[]).find(e=>e.country==='Brasil')}
function initials(name){return String(name||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'A'}
function bookCard(b,label=''){const ed=primaryBrEdition(b),cover=ed?.cover_url||b.cover_url,pub=[ed?.publisher,ed?.publication_year].filter(Boolean).join(' • ');return `<a class="volume-card" href="livro.html?id=${encodeURIComponent(b.id)}">${cover?`<img src="${esc(cover)}" alt="${esc(b.title)}" loading="lazy">`:'<div class="mini-placeholder">Sem capa</div>'}<div>${label?`<small>${esc(label)}</small>`:''}<strong>${esc(b.title)}</strong>${pub?`<span>${esc(pub)}</span>`:''}</div></a>`}
function authorBackHref(){try{const u=new URL(document.referrer);const page=u.pathname.split('/').pop()||'';if(u.origin===location.origin&&page&&page!=='autor.html')return u.href}catch{}return'autores.html'}
function updateAuthorMeta(a,books){let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=(a.bio||`${a.name}: ${books.length} ${books.length===1?'livro':'livros'} cadastrados na Biblioteca Bruta`).slice(0,155);const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=location.href.split('#')[0];document.head.appendChild(canonical);if(a.photo_url){const og=document.createElement('meta');og.setAttribute('property','og:image');og.content=a.photo_url;document.head.appendChild(og)}}
async function loadAuthor(){
 const root=document.getElementById('authorPage'),id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty">Autor não informado.</div>';return}
 const {data:a,error}=await sbAuthor.from('authors').select('id,name,nationality,bio,photo_url,photo_credit,books(id,title,area,cover_url,series_volume,item_type,series(id,name),editions(cover_url,is_primary,country,publisher,publication_year))').eq('id',id).single();if(error||!a){root.innerHTML='<div class="empty">Autor não encontrado.</div>';return}
 document.title=`${a.name} — Biblioteca Bruta`;
 const books=(a.books||[]).sort((x,y)=>String(x.series?.name||'').localeCompare(String(y.series?.name||''),'pt-BR')||(Number(x.series_volume)||9999)-(Number(y.series_volume)||9999)||x.title.localeCompare(y.title,'pt-BR'));
 updateAuthorMeta(a,books);
 const grouped=new Map(),standalone=[];
 for(const b of books){if(b.series?.id){if(!grouped.has(b.series.id))grouped.set(b.series.id,{series:b.series,books:[]});grouped.get(b.series.id).books.push(b)}else standalone.push(b)}
 const seriesGroups=[...grouped.values()].sort((x,y)=>x.series.name.localeCompare(y.series.name,'pt-BR'));
 const seriesCount=seriesGroups.length;
 const heroPhoto=a.photo_url?`<div class="author-photo"><img src="${esc(a.photo_url)}" alt="Foto de ${esc(a.name)}" onerror="this.outerHTML='<div class=&quot;author-photo-placeholder&quot;>${esc(initials(a.name))}</div>'">${a.photo_credit?`<small class="author-photo-credit">${esc(a.photo_credit)}</small>`:''}</div>`:`<div class="author-photo"><div class="author-photo-placeholder">${esc(initials(a.name))}</div></div>`;
 const seriesHtml=seriesGroups.length?seriesGroups.map(g=>`<div class="author-series-block"><div class="author-series-head"><div><h3>${esc(g.series.name)}</h3><span class="muted">${g.books.length} ${g.books.length===1?'livro cadastrado':'livros cadastrados'}</span></div><a href="serie.html?id=${encodeURIComponent(g.series.id)}">Ver página da série →</a></div><div class="series-volume-grid">${g.books.map(b=>bookCard(b,b.item_type==='box'?'BOX / EDIÇÃO ESPECIAL':b.series_volume?`VOLUME ${b.series_volume}`:'VOLUME SEM NUMERAÇÃO')).join('')}</div></div>`).join(''):'';
 const standaloneHtml=standalone.length?`<section class="author-section standalone-block"><div class="author-section-head"><div><h2>Volumes únicos</h2><p>Livros do autor que não fazem parte de uma série cadastrada.</p></div><span class="badge">${standalone.length} ${standalone.length===1?'livro':'livros'}</span></div><div class="series-volume-grid">${standalone.map(b=>bookCard(b,'VOLUME ÚNICO')).join('')}</div></section>`:'';
 const backHref=authorBackHref();
 root.innerHTML=`<div class="context-back-row"><a class="backlink" href="${esc(backHref)}">← Voltar</a>${backHref.endsWith('autores.html')?'':`<a class="backlink secondary-backlink" href="autores.html">Todos os autores</a>`}</div><section class="author-hero">${heroPhoto}<div><div class="eyebrow">AUTOR</div><h1>${esc(a.name)}</h1>${a.nationality?`<div class="author-nationality">${esc(a.nationality)}</div>`:''}${a.bio?`<p class="author-bio">${esc(a.bio)}</p>`:'<p class="author-bio author-empty-bio">Biografia em preparação.</p>'}<div class="author-stats"><div class="author-stat"><small>Livros no catálogo</small><strong>${books.length}</strong></div><div class="author-stat"><small>Séries</small><strong>${seriesCount}</strong></div><div class="author-stat"><small>Volumes únicos</small><strong>${standalone.length}</strong></div></div></div></section>${seriesGroups.length?`<section class="author-section"><div class="author-section-head"><div><h2>Livros por série</h2><p>Obras agrupadas conforme a série cadastrada no catálogo.</p></div><span class="badge">${seriesCount} ${seriesCount===1?'série':'séries'}</span></div>${seriesHtml}</section>`:''}${standaloneHtml}${!books.length?'<section class="author-section"><div class="empty">Nenhum livro deste autor está cadastrado ainda.</div></section>':''}`;
}
document.addEventListener('DOMContentLoaded',loadAuthor);