const sbAuthor=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function primaryBrEdition(b){return (b.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(b.editions||[]).find(e=>e.country==='Brasil')}
function bookSeries(b){const rows=(b.book_series||[]).map(x=>({id:x.series?.id,name:x.series?.name,series_volume:x.series_volume,is_primary:x.is_primary})).filter(x=>x.id);if(rows.length)return rows.sort((a,z)=>(z.is_primary?1:0)-(a.is_primary?1:0)||(a.series_volume??9999)-(z.series_volume??9999));return b.series?.id?[{id:b.series.id,name:b.series.name,series_volume:b.series_volume,is_primary:true}]:[]}
async function loadAuthor(){
  const root=document.getElementById('authorPage'),id=new URLSearchParams(location.search).get('id');
  if(!id){root.innerHTML='<div class="empty">Autor não informado.</div>';return}
  const {data:a,error}=await sbAuthor.from('authors').select(`id,name,nationality,bio,book_authors(author_order,is_primary,books(id,title,area,cover_url,series_volume,series(id,name),book_series(series_volume,is_primary,series(id,name)),editions(cover_url,is_primary,country,publisher,publication_year)))`).eq('id',id).single();
  if(error||!a){root.innerHTML='<div class="empty">Autor não encontrado.</div>';return}
  document.title=`${a.name} — Biblioteca Bruta`;
  const books=(a.book_authors||[]).map(x=>x.books).filter(Boolean);
  books.sort((x,y)=>{const xs=bookSeries(x)[0],ys=bookSeries(y)[0];return String(xs?.name||'').localeCompare(String(ys?.name||''),'pt-BR')||((xs?.series_volume??9999)-(ys?.series_volume??9999))||x.title.localeCompare(y.title,'pt-BR')});
  const seriesMap=new Map();books.forEach(b=>bookSeries(b).forEach(s=>{if(s.id&&!seriesMap.has(s.id))seriesMap.set(s.id,s)}));
  root.innerHTML=`<a class="backlink" href="autores.html">← Todos os autores</a><section class="series-hero"><div class="eyebrow">AUTOR</div><h1>${esc(a.name)}</h1>${a.nationality?`<p class="muted">${esc(a.nationality)}</p>`:''}${a.bio?`<p>${esc(a.bio)}</p>`:''}<div class="series-summary"><strong>${books.length} ${books.length===1?'livro no catálogo':'livros no catálogo'}</strong>${seriesMap.size?`<span class="badge">${seriesMap.size} ${seriesMap.size===1?'série':'séries'}</span>`:''}</div></section>${seriesMap.size?`<section class="detail-section"><h2>Séries</h2><div class="chips">${[...seriesMap.values()].map(s=>`<a class="chip entity-text-link" href="serie.html?id=${encodeURIComponent(s.id)}">${esc(s.name)}</a>`).join('')}</div></section>`:''}<section class="detail-section"><h2>Livros publicados no Brasil</h2><div class="series-volume-grid">${books.map(b=>{const ed=primaryBrEdition(b),c=ed?.cover_url||b.cover_url,pub=[ed?.publisher,ed?.publication_year].filter(Boolean).join(' • '),series=bookSeries(b),primary=series[0];return `<a class="volume-card" href="livro.html?id=${encodeURIComponent(b.id)}">${c?`<img src="${esc(c)}" alt="${esc(b.title)}">`:'<div class="mini-placeholder">Sem capa</div>'}<div>${primary?.series_volume!=null?`<small>VOL. ${esc(primary.series_volume)}</small>`:''}<strong>${esc(b.title)}</strong>${pub?`<span>${esc(pub)}</span>`:''}${series.length?`<span>${esc(series.map(s=>s.name).join(' • '))}</span>`:''}</div></a>`}).join('')}</div></section>`
}
document.addEventListener('DOMContentLoaded',loadAuthor);
