const sbCatalog=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
let catalogRows=[],catalogCategories=[],catalogTags=[],catalogAddedDays=0;
const CATALOG_AREA_GROUPS={
  'Policial/Mistério':['Policial/Mistério','Coleção Negra','Coleção Policial'],
  'Ação / Militar':['Ficção Militar','Ação / Militar'],
  'Horror / Suspense':['Horror / Suspense']
};
function cEsc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function primaryBrEdition(b){return (b.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(b.editions||[]).find(e=>e.country==='Brasil')}
function cAuthors(b){const rows=(b.book_authors||[]).slice().sort((a,z)=>(a.author_order??999)-(z.author_order??999)).map(x=>x.authors).filter(Boolean);return rows.length?rows:(b.authors?[b.authors]:[])}
function cSeries(b){const rows=(b.book_series||[]).map(x=>({id:x.series?.id,name:x.series?.name,brazil_status:x.series?.brazil_status,series_volume:x.series_volume,is_primary:x.is_primary})).filter(x=>x.id);if(rows.length)return rows.sort((a,z)=>(z.is_primary?1:0)-(a.is_primary?1:0)||(a.series_volume??9999)-(z.series_volume??9999));return b.series?.id?[{id:b.series.id,name:b.series.name,brazil_status:b.series.brazil_status,series_volume:b.series_volume,is_primary:true}]:[]}
function cAuthorText(b){return cAuthors(b).map(a=>a.name).filter(Boolean).join(' & ')||'Autor não informado'}
function cSeriesText(b){return cSeries(b).map(s=>`${s.name}${s.series_volume!=null?` · vol. ${s.series_volume}`:''}`).join(' • ')}
function cBookCard(b){const cats=(b.book_categories||[]).map(x=>x.categories?.name).filter(Boolean).join(' • '),tags=(b.book_tags||[]).map(x=>x.tags?.name).filter(Boolean).join(' • '),ed=primaryBrEdition(b),br=[ed?.publisher,ed?.publication_year].filter(Boolean).join(' · '),cover=b.cover_url?`<img src="${cEsc(b.cover_url)}" alt="Capa brasileira de ${cEsc(b.title)}">`:cEsc(b.title),stext=cSeriesText(b);return `<a class="book book-link" href="livro.html?id=${encodeURIComponent(b.id)}"><div class="cover">${cover}</div><div class="book-body"><div class="book-title">${cEsc(b.title)}</div><div class="book-author">${cEsc(cAuthorText(b))}</div>${br?`<div class="book-meta"><strong>Brasil:</strong> ${cEsc(br)}</div>`:''}${stext?`<div class="book-meta">${cEsc(stext)}</div>`:''}${cats?`<div class="book-meta">${cEsc(cats)}</div>`:''}${tags?`<div class="book-meta">${cEsc(tags)}</div>`:''}</div></a>`}
function uniqBy(arr,keyFn){const m=new Map();for(const x of arr){const k=keyFn(x);if(k&&!m.has(k))m.set(k,x)}return [...m.values()]}
function catalogAreasForFilter(area){if(!area)return[];return CATALOG_AREA_GROUPS[area]||[area]}
function normalizeCatalogArea(area){if(area==='Ficção Militar')return'Ação / Militar';if(area==='Policial / Mistério')return'Policial/Mistério';return area}
function attachOptionalRelations(books,authorLinks,seriesLinks){
  const am=new Map(),sm=new Map();
  for(const x of authorLinks||[]){if(!am.has(x.book_id))am.set(x.book_id,[]);am.get(x.book_id).push(x)}
  for(const x of seriesLinks||[]){if(!sm.has(x.book_id))sm.set(x.book_id,[]);sm.get(x.book_id).push(x)}
  for(const b of books||[]){b.book_authors=am.get(b.id)||[];b.book_series=sm.get(b.id)||[]}
  return books||[]
}
async function initCatalog(){
  const [booksRes,catsRes,tagsRes,authorsRes,seriesRes]=await Promise.all([
    sbCatalog.from('books').select('id,title,original_title,area,original_year,cover_url,series_volume,created_at,authors(id,name),series(id,name,brazil_status),book_collections(collections(id,name)),book_categories(categories(id,name,area)),book_tags(tags(id,name)),editions(publisher,publication_year,is_primary,country)').order('title'),
    sbCatalog.from('categories').select('id,name,area').order('name'),
    sbCatalog.from('tags').select('id,name').order('name'),
    sbCatalog.from('book_authors').select('book_id,author_order,is_primary,authors(id,name)').limit(5000),
    sbCatalog.from('book_series').select('book_id,series_volume,is_primary,series(id,name,brazil_status)').limit(5000)
  ]);
  if(booksRes.error){console.error('Erro ao carregar catálogo:',booksRes.error);document.getElementById('filteredCatalog').innerHTML='<div class="empty">Não foi possível carregar o catálogo.</div>';return}
  if(authorsRes.error)console.warn('Autores múltiplos indisponíveis; usando compatibilidade.',authorsRes.error);
  if(seriesRes.error)console.warn('Séries múltiplas indisponíveis; usando compatibilidade.',seriesRes.error);
  catalogRows=attachOptionalRelations(booksRes.data||[],authorsRes.error?[]:authorsRes.data,seriesRes.error?[]:seriesRes.data);
  catalogCategories=catsRes.data||[];catalogTags=tagsRes.data||[];
  populateFilterOptions();restoreFiltersFromUrl();onAreaFilterChange(false);applyCatalogFilters()
}
function fillSelect(id,rows,labelFn,valueFn){const el=document.getElementById(id),first=el.options[0].outerHTML;el.innerHTML=first+rows.map(x=>`<option value="${cEsc(valueFn(x))}">${cEsc(labelFn(x))}</option>`).join('')}
function populateFilterOptions(){fillSelect('filterTag',catalogTags,x=>x.name,x=>x.id);const authors=uniqBy(catalogRows.flatMap(cAuthors),x=>x.id).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));fillSelect('filterAuthor',authors,x=>x.name,x=>x.id);const series=uniqBy(catalogRows.flatMap(cSeries),x=>x.id).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));fillSelect('filterSeries',series,x=>x.name,x=>x.id)}
function onAreaFilterChange(run=true){const area=document.getElementById('filterArea').value,current=document.getElementById('filterCategory').value,areas=catalogAreasForFilter(area),rows=catalogCategories.filter(c=>!area||areas.includes(c.area));fillSelect('filterCategory',rows,x=>x.name,x=>x.id);if(rows.some(x=>x.id===current))document.getElementById('filterCategory').value=current;if(run)applyCatalogFilters()}
function getFilters(){return{q:document.getElementById('filterQ').value.trim(),area:document.getElementById('filterArea').value,category:document.getElementById('filterCategory').value,tag:document.getElementById('filterTag').value,author:document.getElementById('filterAuthor').value,series:document.getElementById('filterSeries').value,status:document.getElementById('filterStatus').value,added:catalogAddedDays,sort:document.getElementById('filterSort').value}}
function applyCatalogFilters(){const f=getFilters(),q=f.q.toLocaleLowerCase('pt-BR'),selectedAreas=catalogAreasForFilter(f.area);let rows=catalogRows.filter(b=>{if(f.added){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(f.added));if(new Date(b.created_at)<cutoff)return false}if(f.area&&!selectedAreas.includes(b.area))return false;if(f.category&&!(b.book_categories||[]).some(x=>x.categories?.id===f.category))return false;if(f.tag&&!(b.book_tags||[]).some(x=>x.tags?.id===f.tag))return false;if(f.author&&!cAuthors(b).some(a=>a.id===f.author))return false;if(f.series&&!cSeries(b).some(s=>s.id===f.series))return false;if(f.status&&!cSeries(b).some(s=>s.brazil_status===f.status))return false;if(q){const hay=[b.title,b.original_title,b.area,...cAuthors(b).map(a=>a.name),...cSeries(b).map(s=>s.name),...(b.book_collections||[]).map(x=>x.collections?.name),...(b.book_categories||[]).map(x=>x.categories?.name),...(b.book_tags||[]).map(x=>x.tags?.name),...(b.editions||[]).map(e=>`${e.publisher||''} ${e.publication_year||''}`)].filter(Boolean).join(' ').toLocaleLowerCase('pt-BR');if(!hay.includes(q))return false}return true});const brYear=b=>primaryBrEdition(b)?.publication_year||0;if(f.sort==='title')rows.sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));else if(f.sort==='author')rows.sort((a,b)=>cAuthorText(a).localeCompare(cAuthorText(b),'pt-BR')||a.title.localeCompare(b.title,'pt-BR'));else if(f.sort==='br_newest')rows.sort((a,b)=>brYear(b)-brYear(a)||a.title.localeCompare(b.title,'pt-BR'));else if(f.sort==='br_oldest')rows.sort((a,b)=>(brYear(a)||9999)-(brYear(b)||9999)||a.title.localeCompare(b.title,'pt-BR'));else if(f.sort==='recent_added')rows.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));document.getElementById('filteredCatalog').innerHTML=rows.length?rows.map(cBookCard).join(''):'<div class="empty">Nenhum livro corresponde a essa combinação de filtros.</div>';document.getElementById('filterSummary').textContent=`${rows.length} ${rows.length===1?'livro encontrado':'livros encontrados'}`;renderActiveFilters(f);syncFiltersToUrl(f)}
function labelFor(selectId){const e=document.getElementById(selectId);return e?.selectedOptions?.[0]?.textContent||''}
function renderActiveFilters(f){const items=[];if(f.q)items.push(['Busca',f.q,'filterQ']);if(f.area)items.push(['Área',labelFor('filterArea')||f.area,'filterArea']);if(f.category)items.push(['Categoria',labelFor('filterCategory'),'filterCategory']);if(f.tag)items.push(['Tema',labelFor('filterTag'),'filterTag']);if(f.author)items.push(['Autor',labelFor('filterAuthor'),'filterAuthor']);if(f.series)items.push(['Série',labelFor('filterSeries'),'filterSeries']);if(f.status)items.push(['Status',f.status,'filterStatus']);if(f.added)items.push(['Cadastro','Últimos '+f.added+' dias','recentAdded']);const box=document.getElementById('activeFilters');box.innerHTML=items.map(([k,v,id])=>`<button class="active-filter" type="button" onclick="${id==='recentAdded'?'clearRecentAdded()':`removeFilter('${id}')`}"><span>${cEsc(k)}:</span> ${cEsc(v)} ×</button>`).join('')}
function clearRecentAdded(){catalogAddedDays=0;applyCatalogFilters()}
function removeFilter(id){const e=document.getElementById(id);if(!e)return;e.value='';if(id==='filterArea')onAreaFilterChange(false);applyCatalogFilters()}
function clearCatalogFilters(){catalogAddedDays=0;['filterQ','filterArea','filterCategory','filterTag','filterAuthor','filterSeries','filterStatus'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.getElementById('filterSort').value='title';onAreaFilterChange(false);applyCatalogFilters()}
function syncFiltersToUrl(f){const p=new URLSearchParams();for(const [k,v] of Object.entries(f)){if(v&&(k!=='sort'||v!=='title'))p.set(k,v)}history.replaceState(null,'',`${location.pathname}${p.toString()?'?'+p.toString():''}`)}
function restoreFiltersFromUrl(){const p=new URLSearchParams(location.search);catalogAddedDays=Math.max(0,Number(p.get('added'))||0);for(const id of ['q','area','tag','author','series','status','sort']){let v=p.get(id);if(!v)continue;if(id==='area')v=normalizeCatalogArea(v);const map={q:'filterQ',area:'filterArea',tag:'filterTag',author:'filterAuthor',series:'filterSeries',status:'filterStatus',sort:'filterSort'},e=document.getElementById(map[id]);if(e)e.value=v}onAreaFilterChange(false);const cat=p.get('category');if(cat)document.getElementById('filterCategory').value=cat}
document.addEventListener('DOMContentLoaded',initCatalog);
