const sbCategory=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
let categoryBooks=[],categoryVisible=48;

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function categoryBackHref(){try{const r=new URL(document.referrer);if(r.origin===location.origin&&!r.pathname.endsWith('/categoria.html'))return r.pathname.split('/').pop()+(r.search||'')}catch{}return'categorias.html'}
function categoryCover(b){const ed=(b.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(b.editions||[]).find(e=>e.country==='Brasil');return{cover:ed?.cover_url||b.cover_url,pub:[ed?.publisher,ed?.publication_year].filter(Boolean).join(' • ')}}
function categoryBookCard(b){const x=categoryCover(b);return `<article class="volume-card taxonomy-book-card"><a class="taxonomy-cover-link" href="livro.html?id=${encodeURIComponent(b.id)}">${x.cover?`<img src="${esc(x.cover)}" alt="Capa de ${esc(b.title)}" loading="lazy">`:'<div class="mini-placeholder">Sem capa</div>'}</a><div class="taxonomy-book-body"><a class="taxonomy-book-title" href="livro.html?id=${encodeURIComponent(b.id)}"><strong>${esc(b.title)}</strong></a>${b.authors?.id?`<a class="entity-text-link" href="autor.html?id=${encodeURIComponent(b.authors.id)}">${esc(b.authors.name||'Autor não informado')}</a>`:`<span>${esc(b.authors?.name||'Autor não informado')}</span>`}${x.pub?`<span>${esc(x.pub)}</span>`:''}${b.series?.id?`<a class="entity-text-link taxonomy-series-link" href="serie.html?id=${encodeURIComponent(b.series.id)}">${esc(b.series.name)}${b.series_volume?` • vol. ${esc(b.series_volume)}`:''}</a>`:''}</div></article>`}
function setCategoryMeta(attr,key,value){if(!value)return;let m=document.head.querySelector(`meta[${attr}="${key}"]`);if(!m){m=document.createElement('meta');m.setAttribute(attr,key);document.head.appendChild(m)}m.content=value}
function updateCategoryMeta(c,books){
 const title=`${c.name} — Biblioteca Bruta`,desc=`Livros da categoria ${c.name} em ${c.area}: ${books.length} ${books.length===1?'título relacionado':'títulos relacionados'} na Biblioteca Bruta.`.slice(0,155),url=`${location.origin}${location.pathname}?id=${encodeURIComponent(c.id)}`;
 let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=desc;
 let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=url;
 setCategoryMeta('property','og:title',title);setCategoryMeta('property','og:description',desc);setCategoryMeta('property','og:url',url);setCategoryMeta('property','og:type','website');
 const data={'@context':'https://schema.org','@type':'CollectionPage',name:title,url,description:desc,isPartOf:{'@type':'WebSite',name:'Biblioteca Bruta',url:'https://bibliotecabruta.com.br/'},about:{'@type':'DefinedTerm',name:c.name,inDefinedTermSet:c.area},mainEntity:{'@type':'ItemList',numberOfItems:books.length,itemListElement:books.slice(0,50).map((b,i)=>({'@type':'ListItem',position:i+1,url:new URL('livro.html?id='+encodeURIComponent(b.id),location.href).href,name:b.title}))}};
 const id='bbCategoryStructuredData';let script=document.getElementById(id);if(!script){script=document.createElement('script');script.type='application/ld+json';script.id=id;document.head.appendChild(script)}script.textContent=JSON.stringify(data);
}
function renderCategoryBooks(){const grid=document.getElementById('categoryBooksGrid'),wrap=document.getElementById('categoryMoreWrap');if(!grid||!wrap)return;const shown=categoryBooks.slice(0,categoryVisible);grid.innerHTML=shown.length?shown.map(categoryBookCard).join(''):'<div class="empty">Nenhum livro associado a esta categoria ainda.</div>';const remaining=Math.max(0,categoryBooks.length-shown.length);wrap.innerHTML=remaining?`<button class="secondary" type="button" onclick="showMoreCategoryBooks()">Mostrar mais ${Math.min(48,remaining)} livros</button><span class="muted">${shown.length} de ${categoryBooks.length}</span>`:categoryBooks.length?`<span class="muted">${categoryBooks.length} ${categoryBooks.length===1?'livro':'livros'} nesta categoria</span>`:''}
function showMoreCategoryBooks(){categoryVisible+=48;renderCategoryBooks()}
function categoryTopEntities(books,key,limit=6){const map=new Map();for(const b of books||[]){const e=b?.[key];if(!e?.id)continue;const row=map.get(e.id)||{...e,count:0};row.count++;map.set(e.id,row)}return[...map.values()].filter(x=>x.count>=2).sort((a,b)=>b.count-a.count||String(a.name||'').localeCompare(String(b.name||''),'pt-BR')).slice(0,limit)}
function categoryCrosslinks(books){const authors=categoryTopEntities(books,'authors'),series=categoryTopEntities(books,'series');if(!authors.length&&!series.length)return'';return `<section class="detail-section"><h2>Mais caminhos nesta categoria</h2><p class="muted">Autores e séries que aparecem com mais frequência neste recorte.</p>${authors.length?`<h3>Autores</h3><div class="chips">${authors.map(x=>`<a class="chip category-link" href="autor.html?id=${encodeURIComponent(x.id)}">${esc(x.name)} · ${x.count}</a>`).join('')}</div>`:''}${series.length?`<h3 style="margin-top:18px">Séries</h3><div class="chips">${series.map(x=>`<a class="chip category-link" href="serie.html?id=${encodeURIComponent(x.id)}">${esc(x.name)} · ${x.count}</a>`).join('')}</div>`:''}</section>`}

async function loadCategory(){
  const root=document.getElementById('categoryPage'),id=new URLSearchParams(location.search).get('id');
  if(!id){root.innerHTML='<div class="empty">Categoria não informada.</div>';return}
  const {data:c,error}=await sbCategory.from('categories').select('id,name,area,book_categories(books(id,title,cover_url,series_volume,authors(id,name),series(id,name),editions(cover_url,is_primary,country,publisher,publication_year)))').eq('id',id).single();
  if(error||!c){root.innerHTML='<div class="empty">Categoria não encontrada.</div>';return}
  document.title=`${c.name} — Biblioteca Bruta`;
  categoryBooks=(c.book_categories||[]).map(x=>x.books).filter(Boolean).sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));categoryVisible=48;updateCategoryMeta(c,categoryBooks);
  const back=categoryBackHref(),crosslinks=categoryCrosslinks(categoryBooks);
  root.innerHTML=`<div class="context-back-row"><a class="backlink" href="${esc(back)}">← Voltar</a>${back!=='categorias.html'?'<a class="secondary-backlink" href="categorias.html">Todas as categorias</a>':''}</div><section class="series-hero taxonomy-detail-hero"><div class="eyebrow">${esc(c.area)}</div><h1>${esc(c.name)}</h1><p class="muted">Prateleira estrutural da Biblioteca Bruta.</p><div class="series-summary"><strong>${categoryBooks.length} ${categoryBooks.length===1?'livro relacionado':'livros relacionados'}</strong></div><div class="taxonomy-detail-actions"><a class="secondary" href="catalogo.html?area=${encodeURIComponent(c.area)}&category=${encodeURIComponent(c.id)}">Abrir no catálogo</a><a class="secondary" href="temas.html?area=${encodeURIComponent(c.area)}">Explorar temas</a></div></section>${crosslinks}<section class="detail-section"><h2>Livros nesta categoria</h2><div id="categoryBooksGrid" class="series-volume-grid"></div><div id="categoryMoreWrap" class="area-catalog-more"></div></section>`;
  renderCategoryBooks();
}

document.addEventListener('DOMContentLoaded',loadCategory);