const sbHomePublic=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
function hpEsc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function goHomeSearch(){const q=(document.getElementById('q')?.value||'').trim();location.href='catalogo.html'+(q?`?q=${encodeURIComponent(q)}`:'')}
function handleHomeSearchKey(e){if(e.key==='Enter'){e.preventDefault();goHomeSearch()}}
async function renderHomeGarimpo(){const tagRoot=document.getElementById('homeTopTags'),catRoot=document.getElementById('homeTopCategories');if(!tagRoot||!catRoot)return;const [{data:books,error},{data:tags},{data:cats}]=await Promise.all([sbHomePublic.from('books').select('book_tags(tags(id,name)),book_categories(categories(id,name))'),sbHomePublic.from('tags').select('id,name'),sbHomePublic.from('categories').select('id,name')]);if(error){tagRoot.innerHTML='<span class="muted">Não foi possível carregar os temas.</span>';catRoot.innerHTML='<span class="muted">Não foi possível carregar as categorias.</span>';return}const tagCounts=new Map(),catCounts=new Map();for(const b of books||[]){for(const x of b.book_tags||[]){const id=x.tags?.id;if(id)tagCounts.set(id,(tagCounts.get(id)||0)+1)}for(const x of b.book_categories||[]){const id=x.categories?.id;if(id)catCounts.set(id,(catCounts.get(id)||0)+1)}}const top=(rows,counts,n)=>[...(rows||[])].map(x=>({...x,count:counts.get(x.id)||0})).filter(x=>x.count>0).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR')).slice(0,n);tagRoot.innerHTML=top(tags,tagCounts,12).map(x=>`<a class="garimpo-link" href="catalogo.html?tag=${encodeURIComponent(x.id)}">${hpEsc(x.name)} <span>${x.count}</span></a>`).join('');catRoot.innerHTML=top(cats,catCounts,8).map(x=>`<a class="garimpo-link" href="catalogo.html?category=${encodeURIComponent(x.id)}">${hpEsc(x.name)} <span>${x.count}</span></a>`).join('')}
async function renderHomeSeries(){const root=document.getElementById('homeSeriesGrid');if(!root)return;const {data,error}=await sbHomePublic.from('series').select('id,name,brazil_status,brazil_published_volumes,original_total_volumes,total_volumes,books(id)').order('name');if(error){root.innerHTML='<div class="empty">Não foi possível carregar as séries.</div>';return}const rows=(data||[]).map(s=>({...s,count:(s.books||[]).length})).filter(s=>s.count>1).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR')).slice(0,4);root.innerHTML=rows.map(s=>{const total=s.original_total_volumes??s.total_volumes;const line=s.brazil_published_volumes!=null&&total?`${s.brazil_published_volumes} de ${total} volumes no Brasil`:s.brazil_published_volumes!=null?`${s.brazil_published_volumes} volumes no Brasil`:`${s.count} volumes no catálogo`;return `<a class="home-series-card" href="serie.html?id=${encodeURIComponent(s.id)}"><small>SÉRIE</small><strong>${hpEsc(s.name)}</strong><span>${hpEsc(line)}${s.brazil_status?` • ${hpEsc(s.brazil_status)}`:''}</span></a>`}).join('')}

function renderRecentBooks(){
 const section=document.getElementById('recentBooksSection'),root=document.getElementById('homeRecentBooks');if(!section||!root)return;
 let rows=[];try{rows=JSON.parse(localStorage.getItem('bb_recent_books')||'[]')}catch{}
 rows=(Array.isArray(rows)?rows:[]).filter(x=>x&&x.id).slice(0,6);
 if(!rows.length){section.classList.add('hidden');return}
 section.classList.remove('hidden');
 root.innerHTML=rows.map(x=>`<a class="book book-link" href="livro.html?id=${encodeURIComponent(x.id)}"><div class="cover">${x.cover?`<img src="${hpEsc(x.cover)}" alt="Capa de ${hpEsc(x.title)}" loading="lazy" onerror="this.remove()">`:hpEsc(x.title)}</div><div class="book-body"><div class="book-title">${hpEsc(x.title)}</div><div class="book-author">${hpEsc(x.author||'')}</div></div></a>`).join('');
}
function clearRecentBooks(){try{localStorage.removeItem('bb_recent_books')}catch{}document.getElementById('recentBooksSection')?.classList.add('hidden')}

document.addEventListener('DOMContentLoaded',()=>{document.getElementById('q')?.addEventListener('keydown',handleHomeSearchKey);renderHomeGarimpo();renderHomeSeries();renderRecentBooks()});