const sbHomePublic=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
window.BB_HOME_BOOKS_PROMISE=window.BB_HOME_BOOKS_PROMISE||(async()=>{
 const {data,error}=await sbHomePublic.from('books').select('id,title,original_title,area,authors(id,name),series(id,name,original_name,brazil_status,brazil_published_volumes,original_total_volumes,total_volumes),book_tags(tags(id,name)),book_categories(categories(id,name,area))');
 return {data:data||[],error};
})();
function hpEsc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function goHomeSearch(){const q=(document.getElementById('q')?.value||'').trim();location.href='catalogo.html'+(q?`?q=${encodeURIComponent(q)}`:'')}
function handleHomeSearchKey(e){if(e.key==='Enter'){e.preventDefault();goHomeSearch()}}
function hpPublicArea(area){if(['Policial/Mistério','Coleção Negra','Coleção Policial'].includes(area))return'Policial/Mistério';if(['Ficção Militar','Ação / Militar'].includes(area))return'Ação / Militar';return area||'Outros'}
function hpBalanced(rowsByArea,limit){const order=['Ficção Histórica','Policial/Mistério','Fantasia','Ficção Científica','Ação / Militar','Horror / Suspense'].filter(a=>rowsByArea.has(a)),out=[],used=new Set();for(let rank=0;out.length<limit;rank++){let added=false;for(const area of order){const row=rowsByArea.get(area)?.[rank];if(!row||used.has(row.id))continue;used.add(row.id);out.push({...row,displayArea:area});added=true;if(out.length>=limit)break}if(!added)break}return out}
function updateHomeAreaCards(books){const configs=[['.area-historica',['Ficção Histórica']],['.area-policial',['Policial/Mistério','Coleção Negra','Coleção Policial']],['.area-fantasia',['Fantasia']],['.area-fc',['Ficção Científica']],['.area-militar',['Ficção Militar','Ação / Militar']],['.area-negra',['Horror / Suspense']]];for(const[selector,areas]of configs){const card=document.querySelector(selector);if(!card)continue;const count=(books||[]).filter(b=>areas.includes(b.area)).length;if(!card.dataset.originalHref&&card.getAttribute('href'))card.dataset.originalHref=card.getAttribute('href');let state=card.querySelector('.area-state');if(!state){state=document.createElement('span');state.className='area-state';card.appendChild(state)}state.textContent=count?`${count} ${count===1?'livro':'livros'}`:'Em preparação';card.classList.toggle('area-empty',!count);if(count){if(card.dataset.originalHref)card.setAttribute('href',card.dataset.originalHref);card.removeAttribute('aria-disabled')}else{card.removeAttribute('href');card.setAttribute('aria-disabled','true')}}}
async function renderHomeGarimpo(){const tagRoot=document.getElementById('homeTopTags'),catRoot=document.getElementById('homeTopCategories');if(!tagRoot||!catRoot)return;const {data:books,error}=await window.BB_HOME_BOOKS_PROMISE;if(error){tagRoot.innerHTML='<span class="muted">Não foi possível carregar os temas.</span>';catRoot.innerHTML='<span class="muted">Não foi possível carregar as categorias.</span>';return}updateHomeAreaCards(books||[]);
 const tagAreaCounts=new Map(),catCounts=new Map(),tagById=new Map(),catById=new Map();
 for(const b of books||[]){const area=hpPublicArea(b.area);for(const x of b.book_tags||[]){const tag=x.tags,id=tag?.id;if(!id)continue;if(!tagById.has(id))tagById.set(id,tag);if(!tagAreaCounts.has(id))tagAreaCounts.set(id,new Map());const m=tagAreaCounts.get(id);m.set(area,(m.get(area)||0)+1)}for(const x of b.book_categories||[]){const cat=x.categories,id=cat?.id;if(!id)continue;if(!catById.has(id))catById.set(id,cat);catCounts.set(id,(catCounts.get(id)||0)+1)}}
 const tagRowsByArea=new Map();for(const [id,areaMap] of tagAreaCounts){for(const [area,count] of areaMap){if(!tagRowsByArea.has(area))tagRowsByArea.set(area,[]);tagRowsByArea.get(area).push({...tagById.get(id),id,count})}}for(const rows of tagRowsByArea.values())rows.sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR'));
 const catRowsByArea=new Map();for(const cat of catById.values()){const count=catCounts.get(cat.id)||0;if(!count)continue;const area=hpPublicArea(cat.area);if(!catRowsByArea.has(area))catRowsByArea.set(area,[]);catRowsByArea.get(area).push({...cat,count})}for(const rows of catRowsByArea.values())rows.sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR'));
 const featuredTags=hpBalanced(tagRowsByArea,12),featuredCats=hpBalanced(catRowsByArea,8);
 tagRoot.innerHTML=featuredTags.map(x=>`<a class="garimpo-link" href="catalogo.html?area=${encodeURIComponent(x.displayArea)}&tag=${encodeURIComponent(x.id)}">${hpEsc(x.name)} <small>${hpEsc(x.displayArea)}</small><span>${x.count}</span></a>`).join('');
 catRoot.innerHTML=featuredCats.map(x=>`<a class="garimpo-link" href="catalogo.html?area=${encodeURIComponent(x.displayArea)}&category=${encodeURIComponent(x.id)}">${hpEsc(x.name)} <small>${hpEsc(x.displayArea)}</small><span>${x.count}</span></a>`).join('')}
async function renderHomeSeries(){const root=document.getElementById('homeSeriesGrid');if(!root)return;const {data:books,error}=await window.BB_HOME_BOOKS_PROMISE;if(error){root.innerHTML='<div class="empty">Não foi possível carregar as séries.</div>';return}
 const seriesMap=new Map();for(const b of books||[]){const s=b.series;if(!s?.id)continue;let row=seriesMap.get(s.id);if(!row){row={...s,books:[]};seriesMap.set(s.id,row)}row.books.push({area:b.area})}
 const rowsByArea=new Map();for(const s of seriesMap.values()){const areaCounts=new Map();for(const b of s.books||[]){const area=hpPublicArea(b.area);areaCounts.set(area,(areaCounts.get(area)||0)+1)}for(const [area,count] of areaCounts){if(count<2)continue;if(!rowsByArea.has(area))rowsByArea.set(area,[]);rowsByArea.get(area).push({...s,count})}}for(const rows of rowsByArea.values())rows.sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR'));
 const rows=hpBalanced(rowsByArea,4);
 root.innerHTML=rows.map(s=>{const total=s.original_total_volumes??s.total_volumes;const line=s.brazil_published_volumes!=null&&total?`${s.brazil_published_volumes} de ${total} volumes no Brasil`:s.brazil_published_volumes!=null?`${s.brazil_published_volumes} volumes no Brasil`:`${s.count} volumes no catálogo`;return `<a class="home-series-card" href="serie.html?id=${encodeURIComponent(s.id)}"><small>SÉRIE · ${hpEsc(s.displayArea)}</small><strong>${hpEsc(s.name)}</strong><span>${hpEsc(line)}${s.brazil_status?` • ${hpEsc(s.brazil_status)}`:''}</span></a>`}).join('')}
function renderRecentBooks(){
 const section=document.getElementById('recentBooksSection'),root=document.getElementById('homeRecentBooks');if(!section||!root)return;
 let rows=[];try{rows=JSON.parse(localStorage.getItem('bb_recent_books')||'[]')}catch{}
 rows=(Array.isArray(rows)?rows:[]).filter(x=>x&&x.id).slice(0,6);
 if(!rows.length){section.classList.add('hidden');return}
 section.classList.remove('hidden');
 root.innerHTML=rows.map(x=>`<a class="book book-link" href="livro.html?id=${encodeURIComponent(x.id)}"><div class="cover">${x.cover?`<img src="${hpEsc(x.cover)}" alt="Capa de ${hpEsc(x.title)}" loading="lazy" onerror="this.remove()">`:hpEsc(x.title)}</div><div class="book-body"><div class="book-title">${hpEsc(x.title)}</div><div class="book-author">${hpEsc(x.author||'')}</div></div></a>`).join('');
}
function clearRecentBooks(){try{localStorage.removeItem('bb_recent_books')}catch{}document.getElementById('recentBooksSection')?.classList.add('hidden')}

document.addEventListener('DOMContentLoaded',()=>{document.getElementById('q')?.addEventListener('keydown',handleHomeSearchKey);renderHomeGarimpo();renderHomeSeries();renderRecentBooks()});