const sbBook=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function val(v,f='—'){return v!==null&&v!==undefined&&v!==''?esc(v):f}
function statusClass(v){const s=String(v||'').toLowerCase();if(s==='completa')return'status-completa';if(s==='interrompida')return'status-interrompida';if(s==='em andamento')return'status-andamento';if(s==='volume único')return'status-volume-unico';return''}
function updateBookMeta(b,cover){let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=(b.synopsis||`${b.title}, de ${b.authors?.name||'autor não informado'}, no catálogo Biblioteca Bruta`).slice(0,155);const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=location.href.split('#')[0];document.head.appendChild(canonical);if(cover){const og=document.createElement('meta');og.setAttribute('property','og:image');og.content=cover;document.head.appendChild(og)}}
async function loadBook(){
 const root=document.getElementById('bookPage'),id=new URLSearchParams(location.search).get('id');
 if(!id){root.innerHTML='<div class="empty">Livro não informado.</div>';return}
 const {data:b,error}=await sbBook.from('books').select('*,authors(id,name,nationality,bio),series(*),book_categories(categories(id,name)),book_tags(tags(id,name)),book_collections(collection_number,collections(id,name,publisher)),editions(*)').eq('id',id).single();
 if(error||!b){root.innerHTML='<div class="empty">Livro não encontrado.</div>';return}
 document.title=`${b.title} — Biblioteca Bruta`;
 const editions=(b.editions||[]).filter(e=>e.country==='Brasil').sort((a,z)=>(z.is_primary?1:0)-(a.is_primary?1:0)||(a.publication_year||9999)-(z.publication_year||9999));
 const primary=editions.find(e=>e.is_primary)||editions[0];const cats=(b.book_categories||[]).map(x=>x.categories).filter(Boolean);const tags=(b.book_tags||[]).map(x=>x.tags).filter(Boolean);const cover=primary?.cover_url||b.cover_url;updateBookMeta(b,cover);
 let siblings=[];if(b.series_id){const {data}=await sbBook.from('books').select('id,title,cover_url,series_volume,editions(cover_url,is_primary,country)').eq('series_id',b.series_id).order('series_volume',{ascending:true});siblings=data||[]}
 const s=b.series,brCount=s?.brazil_published_volumes??siblings.length,origCount=s?.original_total_volumes??s?.total_volumes,status=s?.brazil_status;
 const statusText=brCount!==null&&brCount!==undefined&&origCount?`${brCount} de ${origCount} volumes publicados no Brasil`:brCount?`${brCount} volumes publicados no Brasil`:'';
 const editionCards=editions.length?`<div class="edition-grid">${editions.map(e=>`<article class="edition-card ${e.is_primary?'edition-primary':''}">${e.cover_url?`<img src="${esc(e.cover_url)}" alt="Capa da edição ${esc(e.publisher||'brasileira')}" loading="lazy" onerror="this.remove()">`:''}<div>${e.is_primary?'<span class="edition-primary-label">Edição principal no catálogo</span>':''}<strong>${val(e.publisher,'Editora não informada')}</strong><p>${e.publication_year?esc(e.publication_year):'Ano não informado'}</p>${e.isbn?`<p>ISBN: ${esc(e.isbn)}</p>`:''}${e.translator?`<p>Tradução: ${esc(e.translator)}</p>`:''}${e.pages?`<p>${esc(e.pages)} páginas</p>`:''}${e.notes?`<p>${esc(e.notes)}</p>`:''}</div></article>`).join('')}</div>`:'<p class="muted">Nenhuma edição brasileira detalhada ainda.</p>';
 const seriesFeature=s?.name?`<section class="detail-section series-feature"><h2><a class="series-inline-link" href="serie.html?id=${encodeURIComponent(s.id)}">${esc(s.name)}</a></h2>${statusText||status?`<div class="series-summary">${statusText?`<strong>${esc(statusText)}</strong>`:''}${status?`<span class="badge ${statusClass(status)}">${esc(status)}</span>`:''}</div>`:''}${s.original_name?`<p class="muted">Original: <em>${esc(s.original_name)}</em>${origCount?` • ${esc(origCount)} volumes`:''}</p>`:''}<div class="series-books">${siblings.map(x=>{const ed=(x.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(x.editions||[]).find(e=>e.country==='Brasil');const c=ed?.cover_url||x.cover_url;return `<a href="livro.html?id=${encodeURIComponent(x.id)}" class="series-book ${x.id===b.id?'current':''}">${c?`<img src="${esc(c)}" alt="${esc(x.title)}" loading="lazy" onerror="this.remove()">`:'<div class="mini-placeholder">Sem capa</div>'}<span>${x.series_volume?`${esc(x.series_volume)}. `:''}${esc(x.title)}</span></a>`}).join('')}</div><a class="series-inline-link" href="serie.html?id=${encodeURIComponent(s.id)}">Ver página completa da série →</a></section>`:'';
 root.innerHTML=`<a class="backlink" href="javascript:history.back()">← Voltar ao catálogo</a><section class="book-detail"><div class="book-detail-cover">${cover?`<img src="${esc(cover)}" alt="Capa brasileira de ${esc(b.title)}" onerror="this.onerror=null;this.parentElement.innerHTML='<div class=&quot;cover-placeholder&quot;>Sem capa</div>'">`:'<div class="cover-placeholder">Sem capa</div>'}</div><div class="book-detail-main"><div class="eyebrow">${esc(b.area)}</div><h1>${esc(b.title)}</h1><h2>${b.authors?.id?`<a class="entity-text-link" href="autor.html?id=${encodeURIComponent(b.authors.id)}">${esc(b.authors.name)}</a>`:esc(b.authors?.name||'Autor não informado')}</h2>${s?.name?`<p class="series-line"><span>Parte de <a class="series-inline-link" href="serie.html?id=${encodeURIComponent(s.id)}"><strong>${esc(s.name)}</strong></a></span>${b.series_volume?`<span class="volume-mark">Volume ${esc(b.series_volume)}</span>`:''}</p>`:''}${cats.length?`<div class="classification-block"><small>Categorias</small><div class="chips">${cats.map(c=>`<a class="chip category-link" href="categoria.html?id=${encodeURIComponent(c.id)}">${esc(c.name)}</a>`).join('')}</div></div>`:''}${tags.length?`<div class="classification-block"><small>Temas</small><div class="chips">${tags.map(t=>`<a class="chip tag-link" href="tema.html?id=${encodeURIComponent(t.id)}">${esc(t.name)}</a>`).join('')}</div></div>`:''}${primary?`<div class="br-highlight"><small>EDIÇÃO BRASILEIRA EM DESTAQUE</small><strong>${val(primary.publisher,'Editora não informada')}${primary.publication_year?` • ${esc(primary.publication_year)}`:''}</strong><span>${[primary.pages?`${esc(primary.pages)} páginas`:null,primary.translator?`Tradução: ${esc(primary.translator)}`:null,primary.isbn?`ISBN ${esc(primary.isbn)}`:null].filter(Boolean).join(' • ')}</span></div>`:'<div class="note">Ainda não há edição brasileira detalhada neste cadastro.</div>'}${b.synopsis?`<section class="book-synopsis"><h2>Sobre o livro</h2><p>${esc(b.synopsis)}</p></section>`:''}</div></section><div id="bookUsefulLinks"></div><div class="book-content-grid"><div class="book-content-main"><section class="detail-section"><h2>Edições publicadas no Brasil</h2>${editionCards}</section>${seriesFeature}</div><aside class="book-content-side"><section class="detail-section book-original"><h2>Obra original</h2><div class="facts"><div><small>TÍTULO ORIGINAL</small><strong>${val(b.original_title)}</strong></div><div><small>PUBLICAÇÃO ORIGINAL</small><strong>${val(b.original_year)}</strong></div></div></section>${b.book_collections?.length?`<section class="detail-section"><h2>Coleção editorial</h2><div class="collection-note">${b.book_collections.map(c=>`<p><strong>${esc(c.collections?.name||'')}</strong>${c.collection_number?` — nº ${esc(c.collection_number)}`:''}${c.collections?.publisher?`<br><span class="muted">${esc(c.collections.publisher)}</span>`:''}</p>`).join('')}</div></section>`:''}</aside></div>`;
}
document.addEventListener('DOMContentLoaded',loadBook);