const sbNewsIndex=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
let newsIndexRows=[],newsIndexVisible=12;
function niEsc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function niNorm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR')}
function niHref(n){return n.slug?'noticia.html?slug='+encodeURIComponent(n.slug):'noticia.html?id='+encodeURIComponent(n.id)}
async function initNewsIndex(){const root=document.getElementById('newsIndexGrid');root.innerHTML='<div class="empty">Carregando notícias…</div>';const {data,error}=await sbNewsIndex.from('news').select('id,title,slug,summary,body,image_url,image_alt,published_at,is_featured').eq('is_published',true).lte('published_at',new Date().toISOString()).order('is_featured',{ascending:false}).order('published_at',{ascending:false});if(error){root.innerHTML='<div class="empty">Não foi possível carregar as notícias.</div>';return}newsIndexRows=data||[];const q=new URLSearchParams(location.search).get('q');if(q)document.getElementById('newsSearch').value=q;renderNewsIndex()}
function renderNewsIndex(){const root=document.getElementById('newsIndexGrid'),q=niNorm(document.getElementById('newsSearch')?.value||'').trim();const rows=newsIndexRows.filter(n=>!q||niNorm((n.title||'')+' '+(n.summary||'')+' '+(n.body||'')).includes(q));const visible=rows.slice(0,newsIndexVisible),summary=document.getElementById('newsIndexSummary');summary.textContent=rows.length+' '+(rows.length===1?'notícia encontrada':'notícias encontradas');if(!rows.length){root.innerHTML=newsIndexRows.length?'<div class="news-empty-editorial"><h2>Nenhuma notícia encontrada</h2><p>Tente outra busca ou limpe o campo para ver todas as publicações.</p></div>':'<div class="news-empty-editorial"><h2>Notícias em breve</h2><p>As primeiras novidades editoriais da Biblioteca Bruta aparecerão aqui assim que forem publicadas.</p></div>';document.getElementById('newsIndexMore').innerHTML='';return}root.innerHTML=visible.map(n=>{const image=BB_NEWS.safeUrl(n.image_url),excerpt=n.summary||String(n.body||'').replace(/[#*\[\]()\-]/g,'').slice(0,220);return '<a class="news-list-card '+(n.is_featured?'featured':'')+'" href="'+niHref(n)+'">'+(image?'<div class="news-list-image"><img src="'+niEsc(image)+'" alt="'+niEsc(n.image_alt||n.title)+'" loading="lazy"></div>':'')+'<div class="news-list-body"><div class="news-list-meta">'+(n.is_featured?'<span class="news-featured-badge">DESTAQUE</span>':'')+'<span>'+new Date(n.published_at).toLocaleDateString('pt-BR')+'</span></div><h2>'+niEsc(n.title)+'</h2>'+(excerpt?'<p>'+niEsc(excerpt)+(excerpt.length>=220?'…':'')+'</p>':'')+'<span class="news-list-read">Ler notícia →</span></div></a>'}).join('');const more=document.getElementById('newsIndexMore'),remaining=rows.length-visible.length;more.innerHTML=remaining?'<button class="secondary" type="button" onclick="showMoreNews()">Mostrar mais '+Math.min(12,remaining)+'</button><span class="muted">'+visible.length+' de '+rows.length+'</span>':'';const p=new URLSearchParams();if(document.getElementById('newsSearch').value.trim())p.set('q',document.getElementById('newsSearch').value.trim());history.replaceState(null,'',location.pathname+(p.toString()?'?'+p.toString():''))}
function showMoreNews(){newsIndexVisible+=12;renderNewsIndex()}
function clearNewsSearch(){document.getElementById('newsSearch').value='';newsIndexVisible=12;renderNewsIndex()}
document.addEventListener('DOMContentLoaded',initNewsIndex);