const sbSeries=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function brEdition(book){return (book.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(book.editions||[]).find(e=>e.country==='Brasil')}
function statusClass(v){const s=String(v||'').toLowerCase();if(s==='completa')return'status-completa';if(s==='interrompida')return'status-interrompida';if(s==='em andamento')return'status-andamento';if(s==='volume único')return'status-volume-unico';return''}
function statusSummary(s,catalogued,includeStatus=true){const br=s.brazil_published_volumes;const total=s.original_total_volumes??s.total_volumes;let main='';if(br!=null&&total)main=`${br} de ${total} volumes publicados no Brasil`;else if(br!=null)main=`${br} volumes publicados no Brasil`;else main=`${catalogued} livro${catalogued===1?'':'s'} cadastrado${catalogued===1?'':'s'}`;return `${main}${includeStatus&&s.brazil_status?' — '+s.brazil_status:''}`}
function splitSeriesItems(items){return{volumes:(items||[]).filter(b=>b.item_type!=='box').sort((a,b)=>(a.series_volume||9999)-(b.series_volume||9999)),boxes:(items||[]).filter(b=>b.item_type==='box').sort((a,b)=>(brEdition(b)?.publication_year||9999)-(brEdition(a)?.publication_year||9999))}}
function itemCard(b,label){const ed=brEdition(b),cover=ed?.cover_url||b.cover_url,br=[ed?.publisher,ed?.publication_year].filter(Boolean).join(' • ');return `<a class="volume-card" href="livro.html?id=${encodeURIComponent(b.id)}">${cover?`<img src="${esc(cover)}" alt="${esc(b.title)}">`:'<div class="mini-placeholder">Sem capa</div>'}<div><small>${esc(label)}</small><strong>${esc(b.title)}</strong><span>${esc(b.authors?.name||'')}</span>${br?`<span>${esc(br)}</span>`:''}</div></a>`}
async function getSeries(){const {data,error}=await sbSeries.from('series').select('*,books(id,title,cover_url,series_volume,item_type,authors(name),editions(cover_url,publisher,publication_year,is_primary,country))').order('name');if(error){console.error(error);return []}return data||[]}
async function renderSeries(){const root=document.getElementById('seriesGrid');if(!root)return;root.innerHTML='<div class="empty">Carregando séries…</div>';let rows=await getSeries();const q=(document.getElementById('qSeries')?.value||'').trim().toLowerCase(),status=document.getElementById('statusFilter')?.value||'';rows=rows.filter(s=>(!q||`${s.name} ${s.original_name||''}`.toLowerCase().includes(q))&&(!status||s.brazil_status===status));root.innerHTML=rows.length?rows.map(s=>{const {volumes,boxes}=splitSeriesItems(s.books),first=volumes[0]||boxes[0],ed=first?brEdition(first):null,cover=ed?.cover_url||first?.cover_url;return `<a class="series-card" href="serie.html?id=${encodeURIComponent(s.id)}"><div class="series-card-cover">${cover?`<img src="${esc(cover)}" alt="${esc(s.name)}">`:'<div class="mini-placeholder">Sem capa</div>'}</div><div><div class="eyebrow">SÉRIE</div><h2>${esc(s.name)}</h2><p class="series-status">${esc(statusSummary(s,volumes.length))}</p>${s.brazil_status?`<span class="badge ${statusClass(s.brazil_status)}">${esc(s.brazil_status)}</span>`:''}${s.original_name?`<p class="muted">Original: <em>${esc(s.original_name)}</em></p>`:''}<p>${volumes.length} volume${volumes.length===1?'':'s'} cadastrado${volumes.length===1?'':'s'}${boxes.length?` • ${boxes.length} box`:''}</p></div></a>`}).join(''):'<div class="empty">Nenhuma série encontrada.</div>'}
async function renderSeriesPage(){const root=document.getElementById('seriesPage');if(!root)return;const id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty">Série não informada.</div>';return}const {data:s,error}=await sbSeries.from('series').select('*,books(id,title,original_title,cover_url,series_volume,item_type,authors(name),editions(cover_url,publisher,publication_year,is_primary,country))').eq('id',id).single();if(error||!s){root.innerHTML='<div class="empty">Série não encontrada.</div>';return}const {volumes,boxes}=splitSeriesItems(s.books);document.title=`${s.name} — Biblioteca Bruta`;root.innerHTML=`<a class="backlink" href="series.html">← Todas as séries</a><section class="series-hero"><div><div class="eyebrow">SÉRIE NO BRASIL</div><h1>${esc(s.name)}</h1><div class="series-summary"><strong>${esc(statusSummary(s,volumes.length,false))}</strong>${s.brazil_status?`<span class="badge ${statusClass(s.brazil_status)}">${esc(s.brazil_status)}</span>`:''}</div>${s.description?`<p>${esc(s.description)}</p>`:''}</div></section>${s.original_name||s.original_total_volumes||s.total_volumes?`<section class="detail-section secondary-info"><h2>Referência da série original</h2><div class="facts"><div><small>NOME ORIGINAL</small><strong>${s.original_name?esc(s.original_name):'—'}</strong></div><div><small>TOTAL ORIGINAL</small><strong>${esc(s.original_total_volumes??s.total_volumes??'—')}</strong></div></div></section>`:''}<section class="detail-section"><h2>Volumes cadastrados</h2><p class="muted">A contagem considera apenas os volumes individuais; boxes e edições especiais aparecem separadamente.</p><div class="series-volume-grid">${volumes.length?volumes.map(b=>itemCard(b,b.series_volume?`VOLUME ${b.series_volume}`:'VOLUME')).join(''):'<div class="empty">Nenhum volume cadastrado ainda.</div>'}</div></section>${boxes.length?`<section class="detail-section"><h2>Boxes e edições especiais</h2><div class="series-volume-grid">${boxes.map(b=>itemCard(b,'BOX DA SÉRIE')).join('')}</div></section>`:''}`}
document.addEventListener('DOMContentLoaded',()=>{renderSeries();renderSeriesPage()});
