const sbSeries=window.supabase.createClient(BB_CONFIG.supabaseUrl,BB_CONFIG.supabasePublishableKey);let seriesCache=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function brEdition(book){return (book.editions||[]).find(e=>e.country==='Brasil'&&e.is_primary)||(book.editions||[]).find(e=>e.country==='Brasil')}
function statusClass(v){const s=String(v||'').toLowerCase();if(s==='completa')return'status-completa';if(s==='interrompida')return'status-interrompida';if(s==='em andamento')return'status-andamento';if(s==='volume único')return'status-volume-unico';return''}
function statusSummary(s,catalogued,includeStatus=true){const br=s.brazil_published_volumes;const total=s.original_total_volumes??s.total_volumes;let main='';if(br!=null&&total)main=`${br} de ${total} volumes publicados no Brasil`;else if(br!=null)main=`${br} volumes publicados no Brasil`;else main=`${catalogued} livro${catalogued===1?'':'s'} cadastrado${catalogued===1?'':'s'}`;return `${main}${includeStatus&&s.brazil_status?' — '+s.brazil_status:''}`}
function splitSeriesItems(items){return{volumes:(items||[]).filter(b=>b.item_type!=='box').sort((a,b)=>(Number(a.series_volume)||9999)-(Number(b.series_volume)||9999)||a.title.localeCompare(b.title,'pt-BR')),boxes:(items||[]).filter(b=>b.item_type==='box').sort((a,b)=>(brEdition(b)?.publication_year||9999)-(brEdition(a)?.publication_year||9999))}}
function itemCard(b,label){const ed=brEdition(b),cover=ed?.cover_url||b.cover_url,br=[ed?.publisher,ed?.publication_year].filter(Boolean).join(' • ');return `<a class="volume-card" href="livro.html?id=${encodeURIComponent(b.id)}">${cover?`<img src="${esc(cover)}" alt="${esc(b.title)}" loading="lazy">`:'<div class="mini-placeholder">Sem capa</div>'}<div><small>${esc(label)}</small><strong>${esc(b.title)}</strong><span>${esc(b.authors?.name||'')}</span>${br?`<span>${esc(br)}</span>`:''}</div></a>`}
function seriesBackHref(){try{const u=new URL(document.referrer);const page=u.pathname.split('/').pop()||'';if(u.origin===location.origin&&page&&page!=='serie.html')return u.href}catch{}return'series.html'}
function updateSeriesMeta(s,volumes){const first=volumes[0],cover=first?(brEdition(first)?.cover_url||first.cover_url):null;let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=(s.description||`${s.name}: ${statusSummary(s,volumes.length,false)} no catálogo Biblioteca Bruta`).slice(0,155);const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=location.href.split('#')[0];document.head.appendChild(canonical);if(cover){const og=document.createElement('meta');og.setAttribute('property','og:image');og.content=cover;document.head.appendChild(og)}}
async function getSeries(){if(seriesCache)return seriesCache;const {data,error}=await sbSeries.from('series').select('*,books(id,title,cover_url,series_volume,item_type,authors(id,name),editions(cover_url,publisher,publication_year,is_primary,country))').order('name');if(error){console.error(error);return []}seriesCache=data||[];return seriesCache}
async function renderSeries(){const root=document.getElementById('seriesGrid');if(!root)return;root.innerHTML='<div class="empty">Carregando séries…</div>';let rows=await getSeries();const q=(document.getElementById('qSeries')?.value||'').trim().toLowerCase(),status=document.getElementById('statusFilter')?.value||'';rows=rows.filter(s=>(!q||`${s.name} ${s.original_name||''}`.toLowerCase().includes(q))&&(!status||s.brazil_status===status));root.innerHTML=rows.length?rows.map(s=>{const {volumes,boxes}=splitSeriesItems(s.books),first=volumes[0]||boxes[0],ed=first?brEdition(first):null,cover=ed?.cover_url||first?.cover_url;return `<a class="series-card" href="serie.html?id=${encodeURIComponent(s.id)}"><div class="series-card-cover">${cover?`<img src="${esc(cover)}" alt="${esc(s.name)}">`:'<div class="mini-placeholder">Sem capa</div>'}</div><div><div class="eyebrow">SÉRIE</div><h2>${esc(s.name)}</h2><p class="series-status">${esc(statusSummary(s,volumes.length))}</p>${s.brazil_status?`<span class="badge ${statusClass(s.brazil_status)}">${esc(s.brazil_status)}</span>`:''}${s.original_name?`<p class="muted">Original: <em>${esc(s.original_name)}</em></p>`:''}<p>${volumes.length} volume${volumes.length===1?'':'s'} cadastrado${volumes.length===1?'':'s'}${boxes.length?` • ${boxes.length} box`:''}</p></div></a>`}).join(''):'<div class="empty">Nenhuma série encontrada.</div>'}
async function renderSeriesPage(){
 const root=document.getElementById('seriesPage');if(!root)return;const id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty">Série não informada.</div>';return}
 const {data:s,error}=await sbSeries.from('series').select('*,books(id,title,original_title,cover_url,series_volume,item_type,authors(id,name),editions(cover_url,publisher,publication_year,is_primary,country))').eq('id',id).single();if(error||!s){root.innerHTML='<div class="empty">Série não encontrada.</div>';return}
 const {volumes,boxes}=splitSeriesItems(s.books);document.title=`${s.name} — Biblioteca Bruta`;updateSeriesMeta(s,volumes);
 const br=s.brazil_published_volumes,total=s.original_total_volumes??s.total_volumes,catalogued=volumes.length;const progress=(br!=null&&total)?Math.max(0,Math.min(100,(br/total)*100)):null;const unpublished=(br!=null&&total&&total>br)?total-br:null;
 const authorMap=new Map();for(const v of volumes){if(v.authors?.id&&!authorMap.has(v.authors.id))authorMap.set(v.authors.id,v.authors)}const authors=[...authorMap.values()];
 const authorLinks=authors.length?authors.map(a=>`<a class="series-author-link" href="autor.html?id=${encodeURIComponent(a.id)}">${esc(a.name)}</a>`).join(', '):'—';
 const reference=(s.original_name||total)?`<section class="series-section"><div class="series-section-head"><h2>Referência da série original</h2></div><div class="series-reference"><div class="reference-card"><small>Nome original</small><strong>${s.original_name?esc(s.original_name):'Não informado'}</strong></div><div class="reference-card"><small>Total original</small><strong>${total!=null?`${esc(total)} volume${Number(total)===1?'':'s'}`:'Não informado'}</strong></div></div></section>`:'';
 const gapNote=unpublished?`<div class="series-gap-note"><strong>${esc(unpublished)} volume${unpublished===1?'':'s'} da série original ${unpublished===1?'não consta':'não constam'} como publicado${unpublished===1?'':'s'} no Brasil.</strong> A página mostra apenas os livros que possuem edição brasileira cadastrada no catálogo.</div>`:'';
 root.innerHTML=`<div class="context-back-row"><a class="backlink" href="${esc(seriesBackHref())}">← Voltar</a><a class="backlink secondary-backlink" href="series.html">Todas as séries</a></div><section class="series-hero"><div class="eyebrow">SÉRIE NO BRASIL</div><h1>${esc(s.name)}</h1><div class="series-summary"><strong>${esc(statusSummary(s,catalogued,false))}</strong>${s.brazil_status?`<span class="badge ${statusClass(s.brazil_status)}">${esc(s.brazil_status)}</span>`:''}</div>${s.description?`<p class="series-description">${esc(s.description)}</p>`:''}</section><div class="series-dashboard"><div class="series-stat"><small>Volumes no catálogo</small><strong>${catalogued}</strong></div><div class="series-stat"><small>Publicados no Brasil</small><strong>${br!=null?esc(br):'—'}</strong></div><div class="series-stat"><small>Total original</small><strong>${total!=null?esc(total):'—'}</strong></div><div class="series-stat"><small>Autor${authors.length===1?'':'es'}</small><strong>${authorLinks}</strong></div></div>${progress!==null?`<div class="series-progress-wrap"><div class="series-progress-label"><span>Publicação brasileira da série</span><strong>${Math.round(progress)}%</strong></div><div class="series-progress"><span style="width:${progress}%"></span></div>${gapNote}</div>`:gapNote}<section class="series-section"><div class="series-section-head"><div><h2>Ordem da série</h2><p>Volumes individuais com edição brasileira cadastrada.</p></div><span class="badge">${catalogued} volume${catalogued===1?'':'s'}</span></div><div class="series-volume-grid">${volumes.length?volumes.map(b=>itemCard(b,b.series_volume?`VOLUME ${b.series_volume}`:'VOLUME SEM NUMERAÇÃO')).join(''):'<div class="empty">Nenhum volume cadastrado ainda.</div>'}</div></section>${boxes.length?`<section class="series-section"><div class="series-section-head"><div><h2>Boxes e edições especiais</h2><p>Reuniões e edições que não alteram a numeração dos volumes.</p></div></div><div class="series-volume-grid box-grid">${boxes.map(b=>itemCard(b,'BOX / EDIÇÃO ESPECIAL')).join('')}</div></section>`:''}${reference}`;
}
document.addEventListener('DOMContentLoaded',()=>{renderSeries();renderSeriesPage()});
